### ISSUE TITLE
Implement state persistence within tasks

### ISSUE THREAD

**Issue by rburmorrison** [rburmorrison/commitment#7]
State should be preserved within the same task. For example:

```yaml
subdirectory:
  execute:
    - pwd
    - cd src
    - pwd
    - sleep 10

next:
  execute:
    - pwd
    - sleep 10
```

Should reflect that the second `pwd` in `subdirectory` prints the path to the subdirectory, while the `pwd` in `next` refers to the starting directory again.

It's possible that using a shell as the command and chaining execute steps within the same task will solve this.
